# Chapter 1: Introduction to Python

The goal of this chapter is to provide the required Python programming skills to implement the algorithms presented in the course. We will come back to it at the beginning of every lecture, whenever new concepts are needed.

## Motivations for Python

* Python is very popular in science and engineering: check [SciPy](https://scipy.org), [scikit-learn](http://scikit-learn.org)
* Python is free software ([as in freedom](https://www.fsf.org))
* Python is portable, available for all major operating systems
* Python is a versatile language, "the second best language for everything"


## Limitations relevant to this course
* Can be slower than Matlab in some cases

## Other notes
* Python is an object-oriented language
* Python is an interpreted language

Here we focus on Python 3 (latest version is 3.7). Be careful, there are important differences between Python 3 and Python 2.

## Core Python

### Variables

Variables are typed dynamically:

In [3]:
b = 1 # b is an integer
print(b)

1


In [4]:
b = 2.0*b # now be is a float
print(b)

2.0


### Strings

In [5]:
astring = 'Hello'
another_string = ", World!"
print(astring+another_string) # Concatenation

Hello, World!


In [6]:
print(another_string[2:]) # Slicing

World!


In [7]:
print(another_string[2:-1]) # Slicing again

World


In [8]:
# Strings are immutable
astring[0]
astring[0]='h'

TypeError: 'str' object does not support item assignment

### Tuples

Tuples are sequences of arbitrary objects. They are also immutable.

In [9]:
t = (1, 'one', 'un') # this is a tuple
a, b, c = t # unpacking
print(b)

one


In [10]:
print(t[1])

one


In [11]:
words = t[1:] # slicing
print(words)

('one', 'un')


### Lists

Lists are similar to tuples but they are mutable.

In [12]:
a = [1, 'one']
a.append('un')
print(a)

[1, 'one', 'un']


In [13]:
a.insert(0, '0') # insertion
print(a)

['0', 1, 'one', 'un']


In [14]:
print(len(a)) # length

4


In [15]:
a[1:] = ['foo', 'bar', 'coin'] # slicing and modification
print(a)

['0', 'foo', 'bar', 'coin']


Lists can also be used to define matrices, but numpy arrays are much more convenient (see below).

More on [slicing](https://stackoverflow.com/questions/509211/understanding-pythons-slice-notation).

#### Exercises on slicing

Let a be a list:
1. Create a list containing all the elements in a, except the last 2.
2. Create a list containing only the first 2 elements of a, in reverse.

In [16]:
a = [1, 2, 3, 4, 5]
b = a[:-2]
print(b)

[1, 2, 3]


In [17]:
c = a[1::-1]
print(c)

[2, 1]


### Conditionals

In [20]:
# indentation is part of the language, not just style!
a = 1
if a < 0:
    print('negative')
else:
    print('positive or null')

positive or null


In [21]:
# indentation is part of the language, not just style!
a = 1
if a < 0:
    print('negative')
    else:
    print('positive or null')

SyntaxError: invalid syntax (<ipython-input-21-061c46fa1ded>, line 5)

### Error Control

Python has exception handling:

In [22]:
try:
    a = 1
    a / 0.0
except ZeroDivisionError as e:
    print("you can't do that!")

you can't do that!


### Assertions

Assertions will raise an error when their argument is False, they are a great way to safeguard your code:

In [37]:
def sqrt(x):
    assert(x>=0), "you can't do that either!"
    return x**(0.5)

In [38]:
sqrt(2)

1.4142135623730951

In [39]:
sqrt(-2)

AssertionError: you can't do that either!

### Loops

The for loop requires a sequence of elements to loop over:

In [23]:
# such as a list
a = ['a', 1, 2]
for x in a:
    print(x)

a
1
2


In [28]:
# or a sequence returned by 'range'
for i in range(5):
    print(i)

0
1
2
3
4


In [29]:
### Type conversion

In [30]:
# String to int
a = '1'
b = '2'
print(a+b)


12


In [31]:
print(int(a)+int(b))

3


### References

In [18]:
# Mutable objects are references
a = ['a', 'b', 'c']
b = a # b is a reference, i.e., an 'alias' for a
b[0] = 'qwerty' # Modify b
print(a) # a is modified too

['qwerty', 'b', 'c']


In [19]:
c = a[:] # c is an independent copy of a
c[0] = 'trewq' # Modify c
print(a) # a isn't modified

['qwerty', 'b', 'c']


### Functions

A function is defined using the 'def' keyword:

In [32]:
def my_great_function(a, b, c):
    return (a+b)*c

In [33]:
my_great_function(1, 2, 3)

9

In [34]:
def my_great_function(a, b, c, verbose=False): # last parameter has a default value
    if verbose:
        print("We will do something great")
    return (a-b)*c

In [35]:
my_great_function(1, 2, 3)

-3

In [36]:
my_great_function(1, 2, 3, True)

We will do something great


-3

### Exercise: what's the value of b after my_function was called?

In [47]:
def my_function(x, y):
    x = x + y # also written x+= y
    
b = 3
my_function(b, 2)
print(b)

3


In [48]:
def my_function(x, y):
    x.append(y)
    
b = [ 3 ]
my_function(b, 2)
print(b)

[3, 2]


### Mathematical functions and modules

In [52]:
# Core functions
abs(-1)

1

In [53]:
max(1, 2, 3)

3

In [54]:
# Most functions are in the math module.
# A module is imported like this
import math
math.log(1)

0.0

In [55]:
# Specific functions can also be imported
from math import sin
sin(0)

0.0

In [56]:
# All the functions in a module can be imported
from math import *
cos(0)

1.0

In [57]:
# And in case of name collisions between modules, functions can also be renamed
from math import sqrt as the_right_sqrt
the_right_sqrt(-1)

ValueError: math domain error

### $\texttt{numpy}$ Module

This module introduces array objects similar to lists, but that can be manipulated through numerous functions of the module.

The size of an array is immutable, array elements are mutable.

#### Creating an array

In [58]:
from numpy import array
a = array([1, 2, 3]) # a 1x3 array
print(a)

[1 2 3]


In [76]:
b = array([[0, 1,2],[3, 4, 5]]) # a 2x3 array
print(b)

[[0 1 2]
 [3 4 5]]


In [77]:
from numpy import shape
shape(b) # Getting the shape of an array

(2, 3)

In [60]:
from numpy import zeros
c = zeros((2,3)) # a 2x3 array filled with 0s
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [61]:
from numpy import arange
d = arange(1, 100)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


#### Modifying an array

In [62]:
c[1, 2] = 7
c[0, 0] = 9
print(c)

[[9. 0. 0.]
 [0. 0. 7.]]


In [64]:
# Slicing
c[1,:] # Access row 1

array([0., 0., 7.])

In [65]:
c[:,1] # Access column 1

array([0., 0.])

In [66]:
c[1, 1:] # All the elements of row 1 except the first one

array([0., 7.])

In [67]:
# Slice modification
c[:,1] = [4, 6]
print(c)

[[9. 4. 0.]
 [0. 6. 7.]]


#### Exercise

Write a function that returns an array passed as an argument, except row $i$.

In [88]:
from numpy import *
def remove_row(a, i):
    n, m = shape(a)
    b = zeros((n-1, m))
    for k in range(n-1):
        if k < i:
            b[k] = a[k]
        else:
            b[k] = a[k+1]
    return b

In [89]:
a = array([[0,1],[1,2],[2,3]])
print(remove_row(a, 1))

[[0. 1.]
 [2. 3.]]


#### Operations on arrays

Arithmetic operations are $\underline{\mathrm{broadcast}}$ to all the elements in the array:

In [90]:
a = array([1, 2, 3])
a + 1

array([2, 3, 4])

In [91]:
a / 2

array([0.5, 1. , 1.5])

The mathematical functions available in numpy are also broadcast:

In [92]:
from numpy import sqrt, cos, sin
sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [93]:
cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [94]:
sin(a)

array([0.84147098, 0.90929743, 0.14112001])

Functions imported from the math module won't work on the array:

In [95]:
from math import sqrt
sqrt(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [96]:
sqrt(a[0]) # of course this works!

1.0

#### Array functions

There are many functions in numpy to perform operations on arrays:

In [97]:
from numpy import *
a = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal(a)


array([1, 5, 9])

In [100]:
sum(a)

45

In [101]:
b = array([1, 2, 3])
c = array([4, 5, 6])
dot(b, c)

32

#### Linear algebra module

In [102]:
from numpy import array
from numpy.linalg import inv

a = array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
inv(a) # inverse of a

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

#### Copying arrays

An array is mutable, therefore it is passed as a reference (alias) to functions:

In [103]:
from numpy import array
def do_stuff(a):
    a[0, 0] = 99999
a = array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
do_stuff(a) # this modifies a itself
print(a)

[[99999     2     3]
 [    4     5     6]
 [    7     8    10]]


To work on an individual copy, use the copy function in the numpy module:

In [104]:
from numpy import copy, array
def do_stuff(a):
    a = a.copy()
    a[0, 0] = 99999
a = array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
do_stuff(a) # this doesn't modify a
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


#### Vectorizing Algorithms

Sometimes the broadcasting properties of the mathematical functions in the numpy module can be used to replace loops. For instance, consider the following expression:
$$
s = \sum_{i=1}^{100} i^2
$$

Procedural code:

In [105]:
a = range(100)
s = 0
for i in a:
    s += i**2
print(s)

328350


Vectorized code:

In [106]:
from numpy import *
a = arange(100)
s = sum(power(a, 2))
print(s)

328350


#### Getting help

* Python's built-in help (based on docstrings)

In [107]:
from numpy import tanh
help(tanh)

Help on ufunc object:

tanh = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array 

* [Python reference](https://docs.python.org/3/index.html)
* [Numpy documentation](http://www.scipy.org)
* [Stackoverflow](https://stackoverflow.com)

As with any programming language, practice is the key! The assignments will help you with that.